### ISSUE TITLE
What I'm up to (Glen)

### ISSUE THREAD

**Issue by notnine** [CSC207-UofT/course-project-git-good-207#28]
- Writing Unit tests for a good portion of my functions
- Implementing Unfollowing a user
- Refactoring to avoid smelly code by: splitting up functions into helper functions
- Implementing looking into posts of other users and the currently logged in user (once displayPost is implemented)

**Comment by ericjest** [comment]
Are you done this @notnine

**Comment by notnine** [comment]
Oh yeah this issue has been completed @ericjest
