### ISSUE TITLE
DatabaseDiagram

### ISSUE THREAD

**Issue by sebastianibam002** [CSC207-UofT/course-project-git-good-207#44]
https://dbdiagram.io/d/617c2a4ffa17df5ea67560da
Here is a link for a database diagram I regarding the database setup that is on the main branch

**Comment by ericjest** [comment]
@sebastianibam002 that sounds like a good idea, are we able to set foreign keys with existing IDs from our Java code?

**Comment by sebastianibam002** [comment]
I think it would not work that way, but we might ask the TA tomorrow and check what she thinks

**Comment by ericjest** [comment]
Let's leave this for after the P1 deadline. @sebastianibam002 please ask around and see if you can help with anyone who needs help on their parts. We still have a lot of work left
