### ISSUE TITLE
Error when adding one ingredient in Recipe Creation

### ISSUE THREAD

**Issue by ericjest** [CSC207-UofT/course-project-git-good-207#51]
**Steps to Reproduce**
1. Login
2. Select "Post a Recipe"
3. Enter anything for recipe steps
4. Enter anything when prompted to enter ingredients

**Expected Behaviour**
We should not get an error.

**Actual Behaviour**
The program throws an error and we get an ArrayIndexOutOfBoundsException.

**Comment by ericjest** [comment]
@yowang20 small thing but please close after your fix is merged into main :)

**Comment by yowang20** [comment]
oh ok sorry!
