### ISSUE TITLE
When customizing user profile, username and bio don't update

### ISSUE THREAD

**Issue by ericjest** [CSC207-UofT/course-project-git-good-207#89]
**Steps to reproduce**
1. Customize your User Profile
2. Change your username or bio
3. Now go to "Browse a User Profile"

**Expected Behaviour**
Your username/bio should update

**Actual Behaviour**
Note that your new username doesn't show. Also, if you browse your profile your bio doesn't update.

**Comment by shawnpl7** [comment]
**Suspected Cause**
updateUser in mySQLController is not implemented, so user changes are not saved to the database.

**Comment by ericjest** [comment]
Looks like this is still happening with the User DB methods merged into main, so let's investigate why this is still occurring. @shawnpl7 @sebastianibam002
