### ISSUE TITLE
Confusing message with certain Feed Filters

### ISSUE THREAD

**Issue by ericjest** [CSC207-UofT/course-project-git-good-207#90]
**Steps to reproduce**
1. Browse your Feed.
2. Filter by Recommendations (I think this happens with other Filters too, depending on the state of the app)

Note that the console output says, "Enter a post number for a detailed view of that post or enter 99 to choose a different feed filter".

As a user, I'm not sure what this means. We need a clearer message/user experience. Is it not possible to filter by "recommendations" in this case? What does filtering by recommendations mean?

**Comment by JustinAlianto** [comment]
I will write a message to let the user know if there aren't any posts retrieved from the chosen filter and send the user back to choose a different filter.

**Comment by ericjest** [comment]
@JustinAlianto have you fixed this?
