### ISSUE TITLE
Customizing User Posts is showing a Feed message

### ISSUE THREAD

**Issue by ericjest** [CSC207-UofT/course-project-git-good-207#92]
**Steps to reproduce**
1. Customize your User Profile
2. Select "Posts"

**Expected Behaviour**
We should get some prompt about the our posts.

**Actual Behaviour**
We get a Feed prompt: "Enter a post number for a detailed view of that post or enter 99 to choose a different feed filter"

**Comment by notnine** [comment]
Fixed in my latest PR
